### ISSUE TITLE
[backend]: Setup swagger documentation for backend directory

### ISSUE THREAD

**Issue by akbatra567** [building-for-fun/NetVibe#2]
#  Setup swagger documentation for backend directory

## Description

Please describe the issue you’re facing in as much detail as possible.

## Expected behavior

* Setup swagger documentation for nestjs application
* Create a dummy api to be displayed on swagger doc
* publish the swagger doc on `/api` route.

**Comment by Banh983** [comment]
Hi! I've worked with Swagger documentation before and would love to give this a try. Could you assign this to me so I can help out?

**Comment by Banh983** [comment]
![Screenshot 2024-10-16 192200](https://github.com/user-attachments/assets/ac6e05d7-708b-474a-9766-e23f436a8388)
Here is the image of the current project that i use for swagger documentation

**Comment by akbatra567** [comment]
Hey @Banh983, 
Do have a look at the swagger documentation for nestjs website, so it's aligned with the conventions.

Will assign you the issue.

**Comment by DatHoang102003** [comment]
Hello, I apologize for the inconvenience. The account Banh983 is actually another one of mine, but it’s currently facing some issues, so I’ve switched to this account. I’ve reviewed your backend, and here are the results for the Swagger documentation. I know it might be a bit troublesome, but could you please assign the issue to this account instead?
![image](https://github.com/user-attachments/assets/67d574f1-7fbe-4020-a621-4b13190f977c)

**Comment by DatHoang102003** [comment]
Hello @akbatra567 , it's been quite some time since I initially asked about this issue. I just wanted to check in and see if you still need help with the Swagger documentation or if you've already resolved it.

**Comment by akbatra567** [comment]
> Hello, I apologize for the inconvenience. The account Banh983 is actually another one of mine, but it’s currently facing some issues, so I’ve switched to this account. I’ve reviewed your backend, and here are the results for the Swagger documentation. I know it might be a bit troublesome, but could you please assign the issue to this account instead?
> ![image](https://github.com/user-attachments/assets/67d574f1-7fbe-4020-a621-4b13190f977c)
> 

I hope what you say is true about your own account and not a trick to steal away issues. sure assigning you this, Could you share the PR ?

**Comment by DatHoang102003** [comment]
> > Hello, I apologize for the inconvenience. The account Banh983 is actually another one of mine, but it’s currently facing some issues, so I’ve switched to this account. I’ve reviewed your backend, and here are the results for the Swagger documentation. I know it might be a bit troublesome, but could you please assign the issue to this account instead?
> > ![image](https://private-user-images.githubusercontent.com/170287256/377282112-67d574f1-7fbe-4020-a621-4b13190f977c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTQ1ODksIm5iZiI6MTcyOTIxNDI4OSwicGF0aCI6Ii8xNzAyODcyNTYvMzc3MjgyMTEyLTY3ZDU3NGYxLTdmYmUtNDAyMC1hNjIxLTRiMTMxOTBmOTc3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwMTE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDVkNzkzYmRhNzU0MWQyZTE5MDU4NDkzZTJjMjZiYTcxNGQ1ZTdjZGY3ZGY2MGZkMTE4MjBjZDIxMjFlNzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G__PUO4Gmw7T9oPKtgg5XEjHYoQtomDvWfhnIbLcKqA)
> 
> I hope what you say is true about your own account and not a trick to steal away issues. sure assigning you this, Could you share the PR ?

Hi @akbatra567, I just opened a pull request. Could you clarify if you're asking me to share the PR from my @Banh983 account, or are you referring to the pull request I just submitted?

**Comment by DatHoang102003** [comment]
To address your concern, here's an image of my GitHub account @Banh983. If you need more information, I'd be happy to provide it.
![image](https://github.com/user-attachments/assets/f4dfb56f-5a34-4620-b413-0a5f8df534b0)
